### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ImJakashhi** [Monkvy/selbsthilfegruppe#1]
Bot does not work

**Comment by jinzey** [comment]
true doesnt work anymore

**Comment by MoritzLue24** [comment]
yes, i know i think the ploudos api is kind of broken right now...

**Comment by ImJakashhi** [comment]
can you make it work again?

**Comment by MoritzLue24** [comment]
> can you make it work again?

I currently dont have enough time to fix this but i think looking at the ploudos api implementation for python can help you create your own
